### ISSUE TITLE
Restaurant markers don't animate properly when map zoom is changed

### ISSUE THREAD

**Issue by JeffreyATW** [labzero/lunch#124]

**Comment by nyscherm** [comment]
Sounds like it might be an issue with the 3.31 API release from Google Maps - see [discussion](https://github.com/google-map-react/google-map-react/issues/510#issuecomment-366002128) and version update [notice] (https://groups.google.com/forum/#!topic/google-maps-js-api-v3-notify/cp9SiuHXkFc)
