### ISSUE TITLE
Tag deletion on tag page is buggy

### ISSUE THREAD

**Issue by nyscherm** [labzero/lunch#145]
To recreate: add two or three new tags to a restaurant. Go to the tag page and delete one of the new tags. It will appear as though multiple tags have been deleted.

Then, go back to the main page. Adding a new tag or restaurant results in duplicates being created.

**Comment by nyscherm** [comment]
It appears that when a tag is added/deleted the tag is not added/updated in state properly.

Correct tag objects are formatted:
{id: 4, name: "cat", restaurant_count: "1"}

Adding an existing tag to a restaurant causes the `restaurant_count` to change into a number:
{id: 4, name: "cat", restaurant_count: 2}

Deleting a tag causes the same effect. If there was only one instance of the tag, that tag will remain in tags with `restaurant_count: 0` - probably why said tag still appears on tag page.

Adding a new tag causes a new tag formatted as such:
{id: 4, name: "cat", team_id: 2, updated_at: "2018-03-30T23:15:24.535Z", created_at: "2018-03-30T23:15:24.535Z", restaurant_count: 1}

**Comment by JeffreyATW** [comment]
One solution could be to ensure the API returns numbers for all types of counts. Would improve both the API and the front-end in one fell swoop.

**Comment by nyscherm** [comment]
And fixing that didn't fix it. To be continued
