### ISSUE TITLE
SORT_RESTAURANTS is borked

### ISSUE THREAD

**Issue by JeffreyATW** [labzero/lunch#166]
Restaurants with past decisions get sorted to the top after SORT_RESTAURANTS is dispatched. Should remain at the bottom.

**Comment by nyscherm** [comment]
When SORT_RESTAURANTS is called, it doesn't take into account past decisions, only total votes. So if you mark a past decision on a restaurant that has more votes than the option above it, it will get sorted up. However, restaurant objects in state don't include past decisions (only all_decisions_count).
