### ISSUE TITLE
CI builds keep failing

### ISSUE THREAD

**Issue by JeffreyATW** [labzero/lunch#175]
Maybe try increasing the `slowMo` to 100 and see if anything changes?

**Comment by nyscherm** [comment]
I would just increase `sloMo` by 10 or 20 to start with - if you increase it too much it types so slowly that the tests time out while typing

**Comment by nyscherm** [comment]
PR #230 switched integration testing to Cypress. We'll see if it helps with future PRs?

**Comment by JeffreyATW** [comment]
Closed by #230
