### ISSUE TITLE
Hush Bing crawl errors

### ISSUE THREAD

**Issue by w1150n** [labzero/lunch#53]
It appears that Bing crawls causes these errors:

Message:	Cannot read property 'place_id' of null
Backtrace: 	
restaurants.js  20  .<anonymous>(...)
[PROJECT_ROOT]/webpack:/api/restaurants.js:20:in `.<anonymous>'
URL	GET https://lunch.labzero.com:443/api/restaurants/97/place_url
Location	No Environment specified on cd3c27cff9ea
Browser	Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)

You can see the full error report at:
https://app.honeybadger.io/projects/49826/faults/31294673

**Comment by JeffreyATW** [comment]
I actually just fixed this earlier today: https://github.com/labzero/lunch/commit/38f3ef8f526bcd5506136d09ae1e95f49f6b781d
